### ISSUE TITLE
Figure out the difference between "test" and "clean-test" in the Bechdel .csv file

### ISSUE THREAD

**Issue by aamiller** [aamiller/Info201GroupProj#3]
Some of the codes for the data are not very clear. They need to be investigated to figure out what they are coding for.

**Comment by yan530** [comment]
The difference between test and clean.test:
Test is the evaluation of a hypothesis (It might have many results).
Clean test the one most important variable that causes the result. In other words, the maybe cause by a single variable.
That's why we only see one variable name under the clean.test column.

resource from: https://www.behave.org/conversations/what-is-a-clean-test/
